# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "cm-state-654654512735"
    dynamodb_table = "cm-state-lock-table"
    encrypt        = true
    key            = "./apprunner/terraform.tfstate"
    region         = "us-east-1"
  }
}
